buildserver:
	GOOS=js GOARCH=wasm go build -o output/autogenerated/simastericsgen.wasm cmd/simastericsgen-server/assets/simastericsgen.go
	go build -o output/simastericsgen-server cmd/simastericsgen-server/main.go
	cp cmd/simastericsgen-server/assets/index.html output/
	@if test -f "$$(go env GOROOT)/lib/wasm/wasm_exec.js"; then \
		cp "$$(go env GOROOT)/lib/wasm/wasm_exec.js" output/autogenerated/; \
	else \
		cp "$$(go env GOROOT)/misc/wasm/wasm_exec.js" output/autogenerated/; \
	fi

buildpages:
	rm -rf output
	mkdir -p output/autogenerated
	GOOS=js GOARCH=wasm go build -o output/autogenerated/simastericsgen.wasm cmd/simastericsgen-server/assets/simastericsgen.go
	cp cmd/simastericsgen-server/assets/index.html output/
	@if test -f "$$(go env GOROOT)/lib/wasm/wasm_exec.js"; then \
		cp "$$(go env GOROOT)/lib/wasm/wasm_exec.js" output/autogenerated/; \
	else \
		cp "$$(go env GOROOT)/misc/wasm/wasm_exec.js" output/autogenerated/; \
	fi

buildcli:
	go build -o output/simastericsgen cmd/simastericsgen/main.go

test:
	go test -v $$(go list ./... | grep -v /assets)

clean:
	rm -rf output
